FROM --platform=${BUILDPLATFORM} python:3.11 AS build

ENV PATH="/root/.local/bin:$PATH"

RUN curl -sSL https://install.python-poetry.org | python3 -

COPY pyproject.toml poetry.lock ./

RUN poetry config virtualenvs.create false
RUN poetry install --no-dev


FROM python:3.11-alpine

ENV PYTHONPATH=/opt/python-app/lib

WORKDIR /awesome

COPY --from=build /usr/local/lib/*/site-packages /opt/python-app/lib
COPY src /awesome

CMD ["python3", "main.py"]